# Generated by Django 2.1.4 on 2019-01-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dong_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('medical', models.IntegerField(default=0)),
                ('school', models.IntegerField(default=0)),
                ('house', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infraType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KangwonCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
