# Generated by Django 2.1.4 on 2019-01-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='dong_data',
        ),
    ]
